### ISSUE TITLE
Citation for Publication

### ISSUE THREAD

**Issue by wunderf1tz** [ij-plugins/ijp-toolkit#18]
Dear all,

how would you cite that k-means clustering algorithm from your plugin was used?
Do you have like a standard code for citation that one can use?

Regards,

**Comment by jpsacha** [comment]
As for the implementation you can quote this project page (https://github.com/ij-plugins/ijp-toolkit/). For the description of the k-means algorithm you can use reference provided in [k‐means Clustering Wiki](https://github.com/ij-plugins/ijp-toolkit/wiki/k%E2%80%90means-Clustering):
* Anil K. Jain and Richard C. Dubes, _Algorithms for Clustering Data_, Prentice Hall, 1988. ([PDF version](http://homepages.inf.ed.ac.uk/rbf/BOOKS/JAIN/Clustering_Jain_Dubes.pdf))
* The initialization is done using [k-means++](http://en.wikipedia.org/wiki/K-means%2B%2B) algorithm
